parameters:
    mailer_transport_dsn: 'smtp://aroniainalucas@gmail.com:vbaxuguvnyvmqkde@smtp.gmail.com:587'

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Automatically register all controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Add the mailer service definition (if not already configured)
    Symfony\Component\Mailer\MailerInterface:
        alias: 'mailer.mailer'
