<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241217175945 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pin VARCHAR(6) NOT NULL, date_expiration TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id_utilisateur_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B5852DF3C6EE5C49 ON pin (id_utilisateur_id)');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(30) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE tentative (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre INT NOT NULL, id_utilisateur_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DBC382F9C6EE5C49 ON tentative (id_utilisateur_id)');
        $this->addSql('CREATE TABLE token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(50) NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_expiration TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(30) NOT NULL, email VARCHAR(50) NOT NULL, mdp VARCHAR(255) NOT NULL, id_role_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1D1C63B389E8BDC ON utilisateur (id_role_id)');
        $this->addSql('ALTER TABLE pin ADD CONSTRAINT FK_B5852DF3C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tentative ADD CONSTRAINT FK_DBC382F9C6EE5C49 FOREIGN KEY (id_utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B389E8BDC FOREIGN KEY (id_role_id) REFERENCES role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pin DROP CONSTRAINT FK_B5852DF3C6EE5C49');
        $this->addSql('ALTER TABLE tentative DROP CONSTRAINT FK_DBC382F9C6EE5C49');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B389E8BDC');
        $this->addSql('DROP TABLE pin');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE tentative');
        $this->addSql('DROP TABLE token');
        $this->addSql('DROP TABLE utilisateur');
    }
}
